### ISSUE TITLE
咨询一个问题

### ISSUE THREAD

**Issue by emmataobao** [914245697/spark-hbase#1]
我是将数据流式系统最后进行批次提交，我看你的源码的实现方案，好像是将所有的连接进行广播变量，进行常驻连接，我就是在存入kafka的时候使用过，在流式系统中hbase使用这种方式不知道好不好，还是你借鉴过？

**Comment by Observe-secretly** [comment]
你好。我在开发中发现，SparkStreaming的大部分时间消耗在输出上。即：处理好的数据，在持久化上花费了相当多的时间。它将直接拉低SparkStreaming的整体性能。也就会出现我们常说的算子偏移问题；所以我用广播变量缓存这些连接（它可以是Hbase连接、Mysql、Kafka连接等等），减小输出算子的消耗。这是我的实践经验，如果有异议我们可以再讨论

**Comment by Observe-secretly** [comment]
希望你不要直接拿百度的代码示例直接应用在生产环境。因为上面大部分的内容都只是Demo写法。完全不具备上线的标准。流处理应用每次上线前都需要压测，从而根据实际情况进行调整（这些调整包括你的批次时间、算子的选择和存储的优化），得到最优的配置；

**Comment by emmataobao** [comment]
谢谢你，不好意思没来得及回复。我进行测试，有问题再向你咨询。非常感谢你的回复
