### ISSUE TITLE
我最近看了一部分代码有些问题想咨询一下，希望你回答谢谢。先有5个困惑，剩下的看完再提交。

### ISSUE THREAD

**Issue by emmataobao** [914245697/spark-hbase#2]
1. 我看到好几处广播变量会进行更新，instance.unpersist(); 但是在集群运行时候应该是无法进行更新重新广播的吧。

2.我从代码里没有看到你对kafka偏宜量的处理，以及对数据丢失，或者异常重启数据丢失问题的处理，checkpoint

3. 你处理的binlog数据应该是只有插入我没看到更新操作怎么办？

4.你在保存hbase里面，saveBinlogToHbase这个方法里面为什么要使用  t.collectAsMap(); 不会造成driver端压力过大吗。 

5.你的聚合运算就要在driver端进行执行，会不会影响性能

**Comment by Observe-secretly** [comment]
### 真的很抱歉回复晚了。我下面尝试尽量准确的回答您的问题

- 1、你可能要好好了解下instance.unpersist()的正确使用场景；
- 2、若对数据完整性要求高，你确实要对kafka的offset做单独的处理；
- 3、通常某个表的binlog信息我们使用主键或者自定义唯一组合（你需要自己根据业务场景分析是否组合字段唯一）来做rowkey。当更新操作的binlog来的时候只做insert操作就好了。如果你想说的是hbase的更新操作，那么抱歉。你可能需要再去了解下hbase是如何更新数据的；
- 4、collectAsMap()是一个action操作。再不做聚合的情况下，用它save数据到hbase时，量大确实会有问题。但是好像并没有特别合适的其他方案。通常我们要关心的问题是如何快速的把数据输出到外部存储设备，即提高外部存储设备的吞吐即可。而不是考虑是不是用的action操纵影响程序性能；
- 5、这个问题问的特别好。它会影响性能。这在是代码的早期实现。现在已经不是这么实现的了；

针对第五点我稍微在提醒一下。在做某些运算的时候，它是在driver做还是通过转换函数（如MR）分摊到其他机器算。需要考虑的绝不仅仅是怎么实现更加合理。你需要考虑数据分发在各节点上的成本问题。这个还要结合集群的实际拓扑结构来调整。找到最优的代码实现；有些问题没有直接回答，我相信你可以找到答案；

最后感谢题主阅读代码并提问。
